resource_group_name = "openshift"
node_count = "2" # default 2
master_count = "3" # default 3
infra_count = "3" # default 3
node_vm_size = "Standard_A2m_v2"
master_vm_size = "Standard_A2m_v2"
infra_vm_size = "Standard_A2m_v2"
bastion_vm_size = "Standard_A2"
revproxy_vm_size = "Standard_DS1_v2"
admin_user = "openshift"
admin_password = "OpenShift*36"
# master_domain = "master.mydomain.com"
